services:
  nifi:
    build:
      context: .
      dockerfile: dockerfile.nifi
    container_name: nifi-dp1
    restart: always
    ports:
      - 8443:8443
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
    volumes:
      - ./data:/tmp/data
    networks:
      - dp1_network




  mongo:
    image: mongo:latest
    container_name: mongo-dp1
    restart: always
    ports:
      - "27017:27017"  # Puerto de MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    networks:
      - dp1_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-dp1
    restart: always
    ports:
      - "8081:8081"  # Puerto de Mongo Express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - dp1_network

  dp1:
    build: .
    container_name: dp1
    depends_on:
      - mongo
    ports:
      - "8501:8501"  # Puerto de Streamlit
    networks:
      - dp1_network
    volumes:
      - ./data:/app/data  # Si necesitas persistir datos

networks:
  dp1_network:
    driver: bridge

volumes:
  mongo-data: